### ISSUE TITLE
Messaging service only sends  on "topic" topic

### ISSUE THREAD

**Issue by GalaxyDinoDragonYT** [CompeyDev/roblox.js#2]
If you use messaging service then it only sends the topic as "topic" not what the user requested. I don't know typescript but I think you're missing a ":" before topic in the messaging service file for the URL.

**Comment by CompeyDev** [comment]
You're right, I forgot to set the template placeholder in the urlcat formatter string.

Fixed in https://github.com/CompeyDev/roblox.js/commit/1eacfd1e4f3ed7f12f0413cf204ae946213c33b8.

**Comment by CompeyDev** [comment]
Will publish a release soon, as for now you can use the repository as a git dependency as such:

```json
"rblx.js": "CompeyDev/roblox.js#1eacfd1"
```
